### ISSUE TITLE
output html is not utf-8 encoding

### ISSUE THREAD

**Issue by manuzhang** [lihaoyi/scalatags#113]
The browser can not correctly display my Chinese name. It's ok after I manually added `<meta charset="utf-8" />`

**Comment by lihaoyi** [comment]
That's a browser problem, nothing to do with scalatags

**Comment by lihaoyi** [comment]
you need the `meta charset` thing in all web pages, regardless of scalatags or not :smile:

**Comment by manuzhang** [comment]
exactly, thanks
