### ISSUE TITLE
Unicode characters

### ISSUE THREAD

**Issue by mathieuleclaire** [lihaoyi/scalatags#114]
Hi,
I cannot use unicode characters like ["&#10006;"](http://www.fileformat.info/info/unicode/char/2716/index.htm) because the "&" character is always replaced by "&amp", which leads to a wrong string for my unicode as it can be seen in [Escpaping.scala](https://github.com/lihaoyi/scalatags/blob/master/scalatags/shared/src/main/scala/scalatags/Escaping.scala#L43)

How can I prevent from this ?
Thanks
Mathieu

**Comment by stewSquared** [comment]
@mathieuleclaire For now, you can say something like
```scala
div("Multiplication: 3 ", raw("&#2716"), " 4 == 12")
```
Where you might have said:
```scala
div("Multiplication: 3 &#2716 4 == 12")
```
In the longterm, scalatags should be changed not to escape `&` if it's followed by `#`.

**Comment by mathieuleclaire** [comment]
None of raw("&#2716"), raw("#2716"), raw("&2716"), "&2716", "&#2716" work for me. It still displays the content of the string itself without interpreting the unicode.

**Comment by mathieuleclaire** [comment]
Works with ```scala raw("&#215")```
