### ISSUE TITLE
Update scalatags to 0.6.0

### ISSUE THREAD

**Issue by romainreuillon** [lihaoyi/scalatags#133]
Hi,

we have a project which mixes some libs depending on the latest version of scalatags and on the latest version of scalatex. We get an error because of the API of scalatags 0.6.0 is binary incompatible with 0.5.x. Could you update the scalatags version of scalatex please?

Cheers,
Romain

**Comment by lihaoyi** [comment]
Sure, do you want to re-open this against scalatex? Let's keep track of it there

**Comment by romainreuillon** [comment]
Sure, it was what I intended in the fist place.
