### ISSUE TITLE
publish for Scala 2.12

### ISSUE THREAD

**Issue by antonkulaga** [lihaoyi/scalatags#145]
Please, publish for Scala 2.12

**Comment by SethTisue** [comment]
@larsrh is working on it at https://github.com/lihaoyi/scalatags/pull/142

**Comment by larsrh** [comment]
It's currently number 2 in my queue.

**Comment by larsrh** [comment]
Done.

**Comment by mathieuleclaire** [comment]
Hi,
In which scalatags version number ?
Thanks !

**Comment by larsrh** [comment]
0.6.2

**Comment by vossad01** [comment]
[Releases](https://github.com/lihaoyi/scalatags/releases) hasn't been updated with 0.6.1 or 0.6.2.  I'm not sure if that is intentional or an oversight.

**Comment by larsrh** [comment]
I think this issue can be closed now.

**Comment by Grogs** [comment]
Can you update the homepage (on the `gh-pages` branch)? Currently the docs still reference 0.6.1.

Looks like it's as simple find & replace in index.html, except for the changelog where the entry should be added rather than modified. Unless that file is generated?
