### ISSUE TITLE
Compile error on Option[String]

### ISSUE THREAD

**Issue by bwbecker** [lihaoyi/scalatags#16]
Adding the following to scalatags.BasicTests causes a compile-time error that just seems wrong:

  "OptionString" - {

```
val rd:Option[String] = Some("rd")
val s = rd.getOrElse("")
assert(s.isInstanceOf[String])

val frag = p( rd.getOrElse("") )

assert(frag.toString == """<td>rd</td>""")
```

  }

The error is 

> test-only scalatags.BasicTests
>     [info] Compiling 1 Scala source to /Users/bwbecker/temp/scalaTags/target/scala-2.10/test-classes...
>     [error] /Users/bwbecker/temp/scalaTags/shared/test/scala/scalatags/BasicTests.scala:134: type mismatch;
>     [error]  found   : java.io.Serializable
>     [error]  required: scalatags.Modifier
>     [error]     val frag = p( rd.getOrElse("") )
>     [error]                               ^
>     [error] one error found
>     [error](root/test:compile) Compilation failed
>     [error] Total time: 1 s, completed 24-Feb-2014 8:28:08 AM
>     > 

Substituting _s_ for _rd.getOrElse("")_ compiles just fine.

The tag doesn't seem to make a difference:  it fails on p(...), td(...), and li(...) with the same error.

**Comment by stewSquared** [comment]
I'm a bit late to this thread, but It's worth mentioning for the sake of documentation that adding a type is a simpler fix than having a themporary `val s = ...`

Either of the following will compile:

    p(rd.getOrElse(""): String)
    p(rd.getOrElse[String](""))

It's slightly more verbose, but I think we're all used to occasionally having to add explicit types in scala.

**Comment by lihaoyi** [comment]
Probably not gonna go away any time soon so let's close this
