### ISSUE TITLE
Unable to use top and bottom for vertical-align

### ISSUE THREAD

**Issue by qayshp** [lihaoyi/scalatags#161]
I am trying to set vertical alignment for non-text items in one of my styles, and while there are both workarounds as well as other ways to do this, I would like to have parity with the CSS standard on this.

These two values are listed on [MDN: vertical-align](https://developer.mozilla.org/en-US/docs/Web/CSS/vertical-align), and in the CSS level 1 and level 2 W3C specs.

```
vertical-align: top;
vertical-align: bottom;
```

**Comment by mathieuleclaire** [comment]
095b1135f47bf1be43871fdc32c8050b3a3f5214 fixes it
