### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by pauldraper** [lihaoyi/scalatags#165]
(1) Do you happen to have the code used for the [bencmarks](http://www.lihaoyi.com/scalatags/#Performance) published anywhere?

(2) You link to Twirl for Play 2.2, but 2.3 saw a [significant impovement](https://github.com/playframework/playframework/commit/5c8346e3f8e2a1f2413f3443ca2542ab5ea112e1) in template performance.

(3) I published a ScalaTags/Twirl benchmark at [pauldraper/scala-html-performance](https://github.com/pauldraper/scala-html-performance) with the latest versions of each and a similar tempate. Good news! ScalaTags seems 10-25% faster than Twirl.

**Comment by lihaoyi** [comment]
Some incomplete perf tests are in here https://github.com/lihaoyi/scalatags/blob/master/scalatags/jvm/src/test/scala/scalatags/text/PerfTests.scala#L1

Good to know Scalatags is still faster; probably have Rory Graves to thank for his work speeding things up recently =)

While Scalatags perf is already blazing fast, it still isn't fast enough for *all* use cases. e.g. it was giving me slowdowns when re-rendering large sections of a page client-side, at 60FPS, while scrolling. I'd welcome more improvements, but nothing much else to "fix" here
