### ISSUE TITLE
vue.js guidance

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [lihaoyi/scalatags#174]
vue.js https://vuejs.org/v2/guide/
needs heavy tag/attr customization
perhaps you could write a blog on
how you would support vue.js with scalatags?

**Comment by Andrei-Pozolotin** [comment]
i.e. how to map vue.js spa patterns into tags/attr
https://github.com/skyronic/vue-spa

**Comment by Andrei-Pozolotin** [comment]
i.e. how to make type-safe v-for
```
<div v-for="item in items">
  {{ item.text }}
</div>
```

**Comment by scalway** [comment]
This is a question, not an issue.
there is no good typesafe solution for that... it is still string based API but you can have tags as separate variables.
```scala
import scalatags.JsDom.all._
val vFor = attr("v-for")
val coffe = tag("coffe")

div(
    vFor := "item in items", 
    "{{item.text}}", coffe(
       vFor := "color in item.colors", 
       "{{color.rgb}}"
    )
)

```
https://scalafiddle.io/sf/XmgNWnE/1
You can write your own typesafe API to deal with "item in items" but not sure if it is the best idea.

**Comment by Andrei-Pozolotin** [comment]
that helps, thank you. 

still looking for more-type-safe. i.e.:
```
// type literals
case class Name[T](val name: String) extends AnyVal {
  override def toString = name
}
case class ListName[T](val name: String) extends AnyVal {
  override def toString = name
}

// type safe references
object v {
 val for_ = attr("v-for")
 def forEach[T](item: Name[T], list: ListName[T]) = for_ := s"$item in $list"
}

// ideally these should be "real"  scala-js instances
val item = Name[Int]("item");
val itemList = ListName[Int]("item_list");
div(v.forEach(item, itemList)),
```
