### ISSUE TITLE
How should I create href with a space?

### ISSUE THREAD

**Issue by OndrejSpanel** [lihaoyi/scalatags#204]
Assume following code (the real code is used to access GitHub repository actions):

```scala
import scalatags.Text.all._

val html = a(
   href := s"""https://a.com/page?query=workflow:"Some Name"""",
   "Some Name Actions"
).render
```

The result seems to be:

`<a href="https://a.com/page?query=workflow:&quot;CI Error&quot;">CI Error</a>`

While Chrome accepts such links, I think it is not correct and some user agents (namely Flying Saucer library) reject such hrefs as "containing invalid characters" because of the space in the `CI Error`. I think space in this place should be encoding using `+` (plus sign).

How should I achieve a proper encoding of the href value?

**Comment by Bathtor** [comment]
[URI](https://docs.oracle.com/javase/7/docs/api/java/net/URI.html) generally does the right thing, I think.

**Comment by OndrejSpanel** [comment]
Am I supposed to encode the `href` value somehow, similar to what is done in [how to encode href attribute in HTML](https://stackoverflow.com/a/10189506/16673) ?

I supposed ScalaTags will do The Right Thing on its own, but perhaps it does not in this case.

**Comment by OndrejSpanel** [comment]
> Am I supposed to encode the href value somehow,

It seems I am.
