### ISSUE TITLE
please add "selected" tag, for use with `option`

### ISSUE THREAD

**Issue by fommil** [lihaoyi/scalatags#64]
otherwise we have to `"selected".attr = ""` (which isn't entirely true because it doesn't need a value, I'm just not sure how to do that).

**Comment by lihaoyi** [comment]
Want to send a PR? Like in https://github.com/lihaoyi/scalatags/commit/27ed3e678e37ed826b5753583e0fba23893ffbff. Scalatags generates valid XHTML, so something like `"selected".attr := "selected"` should work

**Comment by fommil** [comment]
if you caught me yesterday, but now I've wrapped up the project I was working on :smile: thanks for all your work on scalajs, it let me turn my small app into this webapp http://fommil.github.io/kerbal/

**Comment by reid-spencer** [comment]
My patch, #63 (merged but unreleased), provides the selected attribute as a boolean attribute so all you have to do is add `selected` to your tag. See [this line](https://github.com/reactific/scalatags/commit/4d890cfadda5150ee7d0468cf5cfc77b0de3fbb5#diff-5940b76c57caeb26c7de464259acb6d6R430) for the definition.

**Comment by lihaoyi** [comment]
I didn't even notice. THanks @reid-spencer!
