### ISSUE TITLE
script tag, not generating a closing tag if used without inline script

### ISSUE THREAD

**Issue by SRGOM** [lihaoyi/scalatags#71]
Hello, when using script tag, without any inline script, e.g.:

    script( src := "/addr.js" )

the tag that gets generated is `<script src = "/addr.js"/>`

and not `<script src = "/addr.js"></script>`

as one would want. What could I be doing wrong? Thanks

**Comment by lihaoyi** [comment]
We have a test that verifies that this doesn't happen

https://github.com/lihaoyi/scalatags/blob/master/scalatags/shared/src/test/scala/scalatags/generic/ExampleTests.scala#L13-L42

My money is that someone else, somewhere else in your code is doing this

**Comment by lihaoyi** [comment]
e.g. see https://github.com/lihaoyi/scalatags/issues/48
