### ISSUE TITLE
Virtual dom

### ISSUE THREAD

**Issue by q42mark** [lihaoyi/scalatags#73]
How hard would it be to implement Virtual DOM (like Facebook React, render the tree, diff trees, update) in terms of scalatags? In combination with Signals/Observable types it would be nice to use pure functions to re-render each time when "something" occurs. With Virtual DOM it should only update the parts which have been changed, so the experience stays smooth and performant. Elm does this aswell: http://elm-lang.org/blog/Blazing-Fast-Html.elm. More about this: https://github.com/evancz/elm-architecture-tutorial

**Comment by q42mark** [comment]
See javascript impl: https://github.com/Matt-Esch/virtual-dom

**Comment by lihaoyi** [comment]
You could easily write bindings for Scalatags to whatever framework you want, e.g. @japgolly wrote some for React.js itself https://github.com/japgolly/scalajs-react) which took a few hundred LOC (not much). Re-implementing the logic from first principles is possible but will take a bit more work.

Realistically, I'm not going to do it anytime soon. Feel free to go do it, it's not hard ^_^
