### ISSUE TITLE
CSS suggestions

### ISSUE THREAD

**Issue by acjay** [lihaoyi/scalatags#78]
There are these nice, typesafe constants for the predefined CSS colors, but they're only available for the `color` property. It seems like these could be factored into a trait that all compatible properties could extend to also take advantage. I don't mind doing this and make a PR if this is a direction you'd be interested in this. 

There could also be support for `transparent`, `currentColor`, and color constants above Level 1 (see https://developer.mozilla.org/en-US/docs/Web/CSS/color_value). I guess it's a question of what level of completeness you're interested in shooting for.

Also, I was wondering if there's any idea of supporting multi-value syntax in the DSL. For example, by using tuples: `margin := (10.px, 10.px)` to get `margin: 10px 10px;`, perhaps specified dynamically by being able to map from tuple arity to the properties aggregated, to allow for the typesafe shorthands to be used somehow.

**Comment by stewSquared** [comment]
In response to your side note about multi-value syntax:

That I can think of, only border, padding, and margin have multiple values, and they're not necessarily all of the same type. I don't think a tuple would be a clean and general solution. On the other hand, you can already write the following, which is just as concise: `margin:=10.px+" "+10.px`

**Comment by acjay** [comment]
There are waaay more properties than that that have multiple values. Look at https://developer.mozilla.org/en-US/docs/Web/CSS/Reference; many (most? all?) of the properties whose names are prefixes of other properties are shorthand properties. Now, I'm not sure if a goal of this project is to eventually capture the whole spec, but given that some thought has already been put into reifying CSS property values, I'm just bringing up the idea of devising a system for extending this to multi-value properties. The reason tuples are attractive for this is that they can capture the fact that a given short-hand property has a definitive set of possible arity/type combinations. If concisessness were the only concern, we could just write pure CSS and be done with it.

**Comment by lihaoyi** [comment]
I'm probably going to go with something like

```scala
def tupleNStyle[T1: StyleValue, T2: StyleValue, ..., Tn: StyleValue](t1: T1, t2: T2, ..., tn: Tn): StyleValue 
def tupleNStyle[T1: PixelStyleValue, T2: PixelStyleValue, ..., Tn: PixelStyleValue](t1: T1, t2: T2, ..., tn: Tn): StyleValue 
```

And just leave it at that. I don't feel like modeling the huge mess of possible CSS properties would be worth it.

**Comment by marklister** [comment]
https://github.com/sbt/sbt-boilerplate is one way to automate generation of def `tupleStyleN [....`

**Comment by marklister** [comment]
I have a fork of sbt-boilerplate that, among other things, searches the shared directory for templates.  I use it as a source dependency in https://github.com/marklister/product-collections which is a cross compiled project.  The dependency is set up in the project/project directory.

**Comment by lihaoyi** [comment]
This is probably not going to happen given the lack of activity over the past year...
