### ISSUE TITLE
Missing scaladocs site

### ISSUE THREAD

**Issue by stewSquared** [lihaoyi/scalatags#79]
It used to be up at github.io/scalatags. Will it now be at another url?

**Comment by ruggy** [comment]
I would like to second this question - now I need to generate scaladocs in order to view the API. Have the API docs been moved to an accessible URL? Thanks!

**Comment by bwbecker** [comment]
I'll add my voice as well.  One of my biggest frustrations (not that there are many!) in using scalatags is figuring out where a given attribute/tag "lives" -- where I should import it from.  I would think readily accessible scaladoc would help.

**Comment by tomjridge** [comment]
Yes, please can the scaladoc be put online somewhere and linked from the other documentation?

Great project.

**Comment by lihaoyi** [comment]
Since there's demand, let me make an offer: if one of you builds the Scaladoc, adds it to the `gh-pages` branch, and adds a link to the Scalatex readme, I'll take the PR ^_^ Building it should be as simple matter of running `scalatagsJS/doc`

**Comment by lihaoyi** [comment]
Fixed in 0.5.3; there's now a link in the readme http://lihaoyi.github.io/scalatags/.  =)
