### ISSUE TITLE
rowspan attribute is missing

### ISSUE THREAD

**Issue by bwbecker** [lihaoyi/scalatags#81]
A grep of the course doesn't find the "rowspan" attribute for td tags.  See http://www.w3.org/TR/html401/struct/tables.html#h-11.2.6.1

**Comment by marklister** [comment]
```scala
scala> td(rowspan:=4)
res6: scalatags.Text.TypedTag[String] = <td rowspan="4"></td>

scala> th(rowspan:=3)
res8: scalatags.Text.TypedTag[String] = <th rowspan="3"></th>
```

I'm running master

**Comment by marklister** [comment]
https://github.com/lihaoyi/scalatags/search?utf8=%E2%9C%93&q=rowspan

scalatags/shared/src/main/scala/scalatags/generic/Attrs.scala  line 973

**Comment by bwbecker** [comment]
[Embarrassed grimace…]  Thanks, Mark.  I was grepping out of date sources :(

Byron

> On Apr 17, 2015, at 10:06 AM, mark lister <notifications@github.com> wrote:
> 
> scala> td(rowspan:=4)
> res6: scalatags.Text.TypedTag[String] = <td rowspan="4"></td>
> 
> scala> th(rowspan:=3)
> res8: scalatags.Text.TypedTag[String] = <th rowspan="3"></th>
> I'm running master
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/lihaoyi/scalatags/issues/81#issuecomment-93992518>.
> 


---------------------------------------------
Byron Weber Becker
School of Computer Science
University of Waterloo, Waterloo, Ontario  N2L 3G1
Email: bwbecker@uwaterloo.ca
Phone:  519-888-4567 x34661
Fax:  519-888-4380 (include my email on cover page)

Advising FAQ:  www.cs.uwaterloo.ca/current/faq

**Comment by marklister** [comment]
@bwbecker, is it possible to close this issue?
