### ISSUE TITLE
title doesn't work as expected

### ISSUE THREAD

**Issue by ngbinh** [lihaoyi/scalatags#82]
More context here: http://stackoverflow.com/questions/29126824/using-title-with-scalatags

```
import scalatags.Text.all._
title("My Awesome Website")
```

But 

```
import scalatags.Text.tags2.title
```
works

**Comment by lihaoyi** [comment]
Yeah, it seems like a natural consequence of stuffing all tags and attributes and styles into the sam giant namespace. Same problem with `style` and other things.

What do you think we should do? Maybe we could leave the tag-version in, and add an implicit to convert it from `tag` to `style` automatically?

**Comment by ngbinh** [comment]
I think the cleanest way is to separate tags and attributes. That's way we can use 
` tags.title ` and `attrs.title` in the same file.

**Comment by lihaoyi** [comment]
You can already do that; `import scalatags.Text.{tags2 => tags, attrs => attrs}` and you're on your way ^_^

**Comment by lihaoyi** [comment]
Closing because it seems there's a solution that does exactly what you want.

**Comment by ngbinh** [comment]
:+1:
