### ISSUE TITLE
Integration with scalite

### ISSUE THREAD

**Issue by HerringtonDarkholme** [lihaoyi/scalatags#91]
Scalatags provides great type safety to html template. But it also begets loads of parentheses/curly braces .

I wonder whether Scalite is still under maintenance so that we can try out its integration with Scalatags ?

**Comment by lihaoyi** [comment]
go ahead and try it out

**Comment by HerringtonDarkholme** [comment]
This is impossible for now. Because function call cannot be sugared into block
