### ISSUE TITLE
Documentation broken link

### ISSUE THREAD

**Issue by cyberjar09** [lihaoyi/scalatags#98]
documentation has a broken link in the text "tiny amount of code" which links to http://lihaoyi.github.io/scalatags/shared/main/scala/scalatags/generic/Core.scala and returns a 404. The actual page needs to be https://github.com/lihaoyi/scalatags/blob/master/scalatags/shared/src/main/scala/scalatags/generic/Core.scala

**Comment by lihaoyi** [comment]
Fixed in 0.5.3; thanks!
